In [7]:
pip install requests

Requirement already satisfied: requests in c:\Users\Azizbek\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Azizbek\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Azizbek\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\Azizbek\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\Azizbek\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import requests

username = "Azizbek4254"
url = f"https://api.chess.com/pub/player/{username}/games/archives"
response = requests.get(url, headers={"User-Agent": "Azizbek4254 - personal data pull"})
archives = response.json()["archives"]
print(archives)

['https://api.chess.com/pub/player/azizbek4254/games/2025/02', 'https://api.chess.com/pub/player/azizbek4254/games/2025/03', 'https://api.chess.com/pub/player/azizbek4254/games/2025/04', 'https://api.chess.com/pub/player/azizbek4254/games/2025/05', 'https://api.chess.com/pub/player/azizbek4254/games/2025/06', 'https://api.chess.com/pub/player/azizbek4254/games/2025/07', 'https://api.chess.com/pub/player/azizbek4254/games/2025/08', 'https://api.chess.com/pub/player/azizbek4254/games/2025/09', 'https://api.chess.com/pub/player/azizbek4254/games/2025/10', 'https://api.chess.com/pub/player/azizbek4254/games/2025/11', 'https://api.chess.com/pub/player/azizbek4254/games/2025/12', 'https://api.chess.com/pub/player/azizbek4254/games/2026/01', 'https://api.chess.com/pub/player/azizbek4254/games/2026/02', 'https://api.chess.com/pub/player/azizbek4254/games/2026/03', 'https://api.chess.com/pub/player/azizbek4254/games/2026/04', 'https://api.chess.com/pub/player/azizbek4254/games/2026/05', 'https://api.chess.com/pub/player/azizbek4254/games/2026/06', 'https://api.chess.com/pub/player/azizbek4254/games/2026/07', 'https://api.chess.com/pub/player/azizbek4254/games/2026/08', 'https://api.chess.com/pub/player/azizbek4254/games/2026/09']

In [9]:
all_games = []
for archive_url in archives:
    resp = requests.get(archive_url, headers={"User-Agent": "Azizbek4254 - personal data pull"})
    all_games.extend(resp.json()["games"])

print(f"Total games: {len(all_games)}")

Total games: 2843

In [10]:
import json
print(json.dumps(all_games[0], indent=2))

{
  "url": "https://www.chess.com/game/live/132851393005",
  "pgn": "[Event \"Live Chess\"]\n[Site \"Chess.com\"]\n[Date \"2025.02.09\"]\n[Round \"-\"]\n[White \"Azizbek4254\"]\n[Black \"The_Fork_Whisperer\"]\n[Result \"0-1\"]\n[CurrentPosition \"8/1p2PqP1/1k6/8/8/3KP3/8/6r1 w - - 0 54\"]\n[Timezone \"UTC\"]\n[ECO \"D04\"]\n[ECOUrl \"https://www.chess.com/openings/Colle-System-3...c6-4.Bd3-Bg4\"]\n[UTCDate \"2025.02.09\"]\n[UTCTime \"14:47:13\"]\n[WhiteElo \"970\"]\n[BlackElo \"1113\"]\n[TimeControl \"180+2\"]\n[Termination \"The_Fork_Whisperer won on time\"]\n[StartTime \"14:47:13\"]\n[EndDate \"2025.02.09\"]\n[EndTime \"14:55:14\"]\n[Link \"https://www.chess.com/game/live/132851393005\"]\n\n1. d4 {[%clk 0:03:01.5]} 1... c6 {[%clk 0:03:01.4]} 2. e3 {[%clk 0:03:03.1]} 2... d5 {[%clk 0:03:02.2]} 3. Bd3 {[%clk 0:03:04.1]} 3... Nf6 {[%clk 0:03:03.5]} 4. Nf3 {[%clk 0:03:04.2]} 4... Bg4 {[%clk 0:03:04]} 5. Bd2 {[%clk 0:03:05]} 5... e6 {[%clk 0:03:04.6]} 6. Nc3 {[%clk 0:03:05]} 6... Bd6 {[%clk 0:03:04.9]} 7. h3 {[%clk 0:03:04.4]} 7... Bh5 {[%clk 0:03:05.5]} 8. g4 {[%clk 0:03:03.8]} 8... Bg6 {[%clk 0:03:06.7]} 9. Bxg6 {[%clk 0:03:03.8]} 9... hxg6 {[%clk 0:03:08.2]} 10. g5 {[%clk 0:03:04.3]} 10... Ne4 {[%clk 0:03:06]} 11. Qe2 {[%clk 0:02:42.2]} 11... Nd7 {[%clk 0:03:02.3]} 12. O-O-O {[%clk 0:02:40.2]} 12... Be7 {[%clk 0:02:57.9]} 13. h4 {[%clk 0:02:38.1]} 13... Qc7 {[%clk 0:02:54.6]} 14. Nxe4 {[%clk 0:02:31.2]} 14... dxe4 {[%clk 0:02:55.2]} 15. Nh2 {[%clk 0:02:10.4]} 15... O-O-O {[%clk 0:02:53.4]} 16. Ng4 {[%clk 0:02:05.2]} 16... Rde8 {[%clk 0:02:50]} 17. f4 {[%clk 0:02:04]} 17... Bd8 {[%clk 0:02:31]} 18. Ne5 {[%clk 0:02:02.2]} 18... Nxe5 {[%clk 0:02:31.6]} 19. dxe5 {[%clk 0:02:00.7]} 19... Be7 {[%clk 0:02:31.5]} 20. Bc3 {[%clk 0:01:54.1]} 20... Rd8 {[%clk 0:02:30.1]} 21. Rd2 {[%clk 0:01:50.2]} 21... Rxd2 {[%clk 0:02:30.9]} 22. Qxd2 {[%clk 0:01:46.6]} 22... Rd8 {[%clk 0:02:29.3]} 23. Qe2 {[%clk 0:01:44.1]} 23... Qb6 {[%clk 0:02:29.1]} 24. Rd1 {[%clk 0:01:40]} 24... Rh8 {[%clk 0:02:27]} 25. Rh1 {[%clk 0:01:24.1]} 25... Bb4 {[%clk 0:02:18.2]} 26. Bxb4 {[%clk 0:01:12.6]} 26... Qxb4 {[%clk 0:02:20.1]} 27. Qd2 {[%clk 0:01:13.6]} 27... Qxd2+ {[%clk 0:02:11.3]} 28. Kxd2 {[%clk 0:01:14]} 28... Kc7 {[%clk 0:02:12.9]} 29. Kc3 {[%clk 0:01:14.8]} 29... Rd8 {[%clk 0:02:07.3]} 30. Kb3 {[%clk 0:01:03.5]} 30... Rd2 {[%clk 0:02:06.6]} 31. Kc3 {[%clk 0:00:43.7]} 31... Re2 {[%clk 0:02:06]} 32. Rh3 {[%clk 0:00:43.6]} 32... Kb6 {[%clk 0:02:00.7]} 33. b3 {[%clk 0:00:39.9]} 33... Kb5 {[%clk 0:02:01.1]} 34. a4+ {[%clk 0:00:39.9]} 34... Ka5 {[%clk 0:01:57.1]} 35. Kd4 {[%clk 0:00:19.4]} 35... Rxc2 {[%clk 0:01:56.1]} 36. Kxe4 {[%clk 0:00:20.7]} 36... Rb2 {[%clk 0:01:53.8]} 37. h5 {[%clk 0:00:21.3]} 37... gxh5 {[%clk 0:01:54.2]} 38. Rxh5 {[%clk 0:00:22.7]} 38... Rxb3 {[%clk 0:01:55.7]} 39. Rh7 {[%clk 0:00:23.9]} 39... Rb4+ {[%clk 0:01:56.9]} 40. Kf3 {[%clk 0:00:23.2]} 40... Rxa4 {[%clk 0:01:53.3]} 41. Rxg7 {[%clk 0:00:24.6]} 41... Ra1 {[%clk 0:01:51.8]} 42. Rxf7 {[%clk 0:00:24.8]} 42... Kb6 {[%clk 0:01:52.9]} 43. g6 {[%clk 0:00:24.8]} 43... Rg1 {[%clk 0:01:54]} 44. g7 {[%clk 0:00:24.9]} 44... c5 {[%clk 0:01:54.5]} 45. Ke4 {[%clk 0:00:21.5]} 45... a5 {[%clk 0:01:53.5]} 46. f5 {[%clk 0:00:22.4]} 46... exf5+ {[%clk 0:01:54.1]} 47. Kxf5 {[%clk 0:00:23.6]} 47... c4 {[%clk 0:01:55.3]} 48. Ke4 {[%clk 0:00:21.8]} 48... a4 {[%clk 0:01:52.4]} 49. Kd4 {[%clk 0:00:19]} 49... a3 {[%clk 0:01:53.9]} 50. e6 {[%clk 0:00:16.7]} 50... a2 {[%clk 0:01:54.4]} 51. e7 {[%clk 0:00:16.8]} 51... a1=Q+ {[%clk 0:01:54.9]} 52. Kxc4 {[%clk 0:00:17.8]} 52... Qa2+ {[%clk 0:01:53.7]} 53. Kd3 {[%clk 0:00:18.6]} 53... Qxf7 {[%clk 0:01:54.8]} 0-1\n",
  "time_control": "180+2",
  "end_time": 1739112914,
  "rated": true,
  "tcn": "lBYQmuZJft!Tgv6Ecl0Sbs9RpxENoENUtU3UEMTCdm5ZecR0xF7YsCJCvp86pE78nD07EKZKBK70ls87dl7lml?7lmYPhd7?dh0zszPzmlzlcl6Yls?7sr7lrslmhxYPjrPHiyHGsBmkBCkjFNUNxNjrN3rzCvzy32ya21GPMUagU2QIvCWGDLSLCLIALCGyCByqKSqiS0i~BAaiAti1",
  "uuid": "bfd57245-e6f4-11ef-b220-6cfe544c0428",
  "initial_setup": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
  "fen": "8/1p2PqP1/1k6/8/8/3KP3/8/6r1 w - - 0 54",
  "time_class": "blitz",
  "rules": "chess",
  "white": {
    "rating": 970,
    "result": "timeout",
    "@id": "https://api.chess.com/pub/player/azizbek4254",
    "username": "Azizbek4254",
    "uuid": "83211c54-e6f4-11ef-8d7f-0106ebca8faa"
  },
  "black": {
    "rating": 1113,
    "result": "win",
    "@id": "https://api.chess.com/pub/player/the_fork_whisperer",
    "username": "The_Fork_Whisperer",
    "uuid": "5e7d8d1c-c4ec-11ef-a962-876ebab3b296"
  },
  "eco": "https://www.chess.com/openings/Colle-System-3...c6-4.Bd3-Bg4"
}

In [11]:
import re

PGN_TAG_RE = re.compile(r'\[(\w+)\s+"(.*?)"\]')

In [12]:
def parse_pgn_tags(pgn: str) -> dict:
    return dict(PGN_TAG_RE.findall(pgn or ""))

In [13]:
tags = parse_pgn_tags(all_games[0]["pgn"])
print(tags)

{'Event': 'Live Chess', 'Site': 'Chess.com', 'Date': '2025.02.09', 'Round': '-', 'White': 'Azizbek4254', 'Black': 'The_Fork_Whisperer', 'Result': '0-1', 'CurrentPosition': '8/1p2PqP1/1k6/8/8/3KP3/8/6r1 w - - 0 54', 'Timezone': 'UTC', 'ECO': 'D04', 'ECOUrl': 'https://www.chess.com/openings/Colle-System-3...c6-4.Bd3-Bg4', 'UTCDate': '2025.02.09', 'UTCTime': '14:47:13', 'WhiteElo': '970', 'BlackElo': '1113', 'TimeControl': '180+2', 'Termination': 'The_Fork_Whisperer won on time', 'StartTime': '14:47:13', 'EndDate': '2025.02.09', 'EndTime': '14:55:14', 'Link': 'https://www.chess.com/game/live/132851393005'}

In [14]:
game = all_games[0]

easy_fields = {
    "time_class": game.get("time_class"),
    "rated": game.get("rated"),
    "rules": game.get("rules"),
    "end_time": game.get("end_time"),
    "white_username": game.get("white", {}).get("username"),
    "white_rating": game.get("white", {}).get("rating"),
    "white_result": game.get("white", {}).get("result"),
    "black_username": game.get("black", {}).get("username"),
    "black_rating": game.get("black", {}).get("rating"),
    "black_result": game.get("black", {}).get("result"),
}

print(easy_fields)

{'time_class': 'blitz', 'rated': True, 'rules': 'chess', 'end_time': 1739112914, 'white_username': 'Azizbek4254', 'white_rating': 970, 'white_result': 'timeout', 'black_username': 'The_Fork_Whisperer', 'black_rating': 1113, 'black_result': 'win'}

In [15]:
row = {**easy_fields, **parse_pgn_tags(game["pgn"])}
print(row)

{'time_class': 'blitz', 'rated': True, 'rules': 'chess', 'end_time': 1739112914, 'white_username': 'Azizbek4254', 'white_rating': 970, 'white_result': 'timeout', 'black_username': 'The_Fork_Whisperer', 'black_rating': 1113, 'black_result': 'win', 'Event': 'Live Chess', 'Site': 'Chess.com', 'Date': '2025.02.09', 'Round': '-', 'White': 'Azizbek4254', 'Black': 'The_Fork_Whisperer', 'Result': '0-1', 'CurrentPosition': '8/1p2PqP1/1k6/8/8/3KP3/8/6r1 w - - 0 54', 'Timezone': 'UTC', 'ECO': 'D04', 'ECOUrl': 'https://www.chess.com/openings/Colle-System-3...c6-4.Bd3-Bg4', 'UTCDate': '2025.02.09', 'UTCTime': '14:47:13', 'WhiteElo': '970', 'BlackElo': '1113', 'TimeControl': '180+2', 'Termination': 'The_Fork_Whisperer won on time', 'StartTime': '14:47:13', 'EndDate': '2025.02.09', 'EndTime': '14:55:14', 'Link': 'https://www.chess.com/game/live/132851393005'}

In [16]:
rows = []

for game in all_games:
    easy_fields = {
        "time_class": game.get("time_class"),
        "rated": game.get("rated"),
        "rules": game.get("rules"),
        "end_time": game.get("end_time"),
        "white_username": game.get("white", {}).get("username"),
        "white_rating": game.get("white", {}).get("rating"),
        "white_result": game.get("white", {}).get("result"),
        "black_username": game.get("black", {}).get("username"),
        "black_rating": game.get("black", {}).get("rating"),
        "black_result": game.get("black", {}).get("result"),
    }
    row = {**easy_fields, **parse_pgn_tags(game["pgn"])}
    rows.append(row)

print(len(rows))
print(rows[0])

2843
{'time_class': 'blitz', 'rated': True, 'rules': 'chess', 'end_time': 1739112914, 'white_username': 'Azizbek4254', 'white_rating': 970, 'white_result': 'timeout', 'black_username': 'The_Fork_Whisperer', 'black_rating': 1113, 'black_result': 'win', 'Event': 'Live Chess', 'Site': 'Chess.com', 'Date': '2025.02.09', 'Round': '-', 'White': 'Azizbek4254', 'Black': 'The_Fork_Whisperer', 'Result': '0-1', 'CurrentPosition': '8/1p2PqP1/1k6/8/8/3KP3/8/6r1 w - - 0 54', 'Timezone': 'UTC', 'ECO': 'D04', 'ECOUrl': 'https://www.chess.com/openings/Colle-System-3...c6-4.Bd3-Bg4', 'UTCDate': '2025.02.09', 'UTCTime': '14:47:13', 'WhiteElo': '970', 'BlackElo': '1113', 'TimeControl': '180+2', 'Termination': 'The_Fork_Whisperer won on time', 'StartTime': '14:47:13', 'EndDate': '2025.02.09', 'EndTime': '14:55:14', 'Link': 'https://www.chess.com/game/live/132851393005'}

In [17]:
import pandas as pd

df = pd.DataFrame(rows)
print(df.shape)
df.head()

(2843, 31)

,time_class,rated,rules,end_time,white_username,white_rating,white_result,black_username,black_rating,black_result,...,UTCDate,UTCTime,WhiteElo,BlackElo,TimeControl,Termination,StartTime,EndDate,EndTime,Link
0,blitz,True,chess,1739112914,Azizbek4254,970,timeout,The_Fork_Whisperer,1113,win,...,2025.02.09,14:47:13,970,1113,180+2,The_Fork_Whisperer won on time,14:47:13,2025.02.09,14:55:14,https://www.chess.com/game/live/132851393005
1,blitz,True,chess,1739113457,Agent_Sunnight,991,win,Azizbek4254,855,checkmated,...,2025.02.09,14:57:26,991,855,180+2,Agent_Sunnight won by checkmate,14:57:26,2025.02.09,15:04:17,https://www.chess.com/game/live/122734683432
2,blitz,True,chess,1739113773,Kirubel0,865,abandoned,Azizbek4254,949,win,...,2025.02.09,15:04:30,865,949,180+2,Azizbek4254 won - game abandoned,15:04:30,2025.02.09,15:09:33,https://www.chess.com/game/live/122734825958
3,blitz,True,chess,1739113893,Azizbek4254,1022,win,dashgooner,951,abandoned,...,2025.02.09,15:09:39,1022,951,180+2,Azizbek4254 won - game abandoned,15:09:39,2025.02.09,15:11:33,https://www.chess.com/game/live/122734930560
4,blitz,True,chess,1739114592,ArturoSuazo18,945,win,Azizbek4254,948,timeout,...,2025.02.09,15:11:39,945,948,180+2,ArturoSuazo18 won on time,15:11:39,2025.02.09,15:23:12,https://www.chess.com/game/live/122734971800

In [18]:
print(df.columns.tolist())

['time_class', 'rated', 'rules', 'end_time', 'white_username', 'white_rating', 'white_result', 'black_username', 'black_rating', 'black_result', 'Event', 'Site', 'Date', 'Round', 'White', 'Black', 'Result', 'CurrentPosition', 'Timezone', 'ECO', 'ECOUrl', 'UTCDate', 'UTCTime', 'WhiteElo', 'BlackElo', 'TimeControl', 'Termination', 'StartTime', 'EndDate', 'EndTime', 'Link']

In [19]:
df.to_csv("all_games_full.csv", index=False)

In [20]:
df = df.drop(columns=[
    "rated",
    "rules",
    "Event",
    "Site",
    "Round",
    "White",
    "Black",
    "CurrentPosition",
    "Timezone",
    "ECO",
    "ECOUrl",
    "UTCDate",
    "UTCTime",
    "Link",
])

print(df.shape)
df.head()

(2843, 17)

,time_class,end_time,white_username,white_rating,white_result,black_username,black_rating,black_result,Date,Result,WhiteElo,BlackElo,TimeControl,Termination,StartTime,EndDate,EndTime
0,blitz,1739112914,Azizbek4254,970,timeout,The_Fork_Whisperer,1113,win,2025.02.09,0-1,970,1113,180+2,The_Fork_Whisperer won on time,14:47:13,2025.02.09,14:55:14
1,blitz,1739113457,Agent_Sunnight,991,win,Azizbek4254,855,checkmated,2025.02.09,1-0,991,855,180+2,Agent_Sunnight won by checkmate,14:57:26,2025.02.09,15:04:17
2,blitz,1739113773,Kirubel0,865,abandoned,Azizbek4254,949,win,2025.02.09,0-1,865,949,180+2,Azizbek4254 won - game abandoned,15:04:30,2025.02.09,15:09:33
3,blitz,1739113893,Azizbek4254,1022,win,dashgooner,951,abandoned,2025.02.09,1-0,1022,951,180+2,Azizbek4254 won - game abandoned,15:09:39,2025.02.09,15:11:33
4,blitz,1739114592,ArturoSuazo18,945,win,Azizbek4254,948,timeout,2025.02.09,1-0,945,948,180+2,ArturoSuazo18 won on time,15:11:39,2025.02.09,15:23:12

In [21]:
df.to_csv("chess_games_clean.csv", index=False)

In [22]:
df["start_datetime"] = pd.to_datetime(df["Date"] + " " + df["StartTime"], format="%Y.%m.%d %H:%M:%S")
df["end_datetime"] = pd.to_datetime(df["EndDate"] + " " + df["EndTime"], format="%Y.%m.%d %H:%M:%S")

df[["start_datetime", "end_datetime"]].head()

       start_datetime        end_datetime
0 2025-02-09 14:47:13 2025-02-09 14:55:14
1 2025-02-09 14:57:26 2025-02-09 15:04:17
2 2025-02-09 15:04:30 2025-02-09 15:09:33
3 2025-02-09 15:09:39 2025-02-09 15:11:33
4 2025-02-09 15:11:39 2025-02-09 15:23:12

In [23]:
df["duration"] = df["end_datetime"] - df["start_datetime"]

df["duration"].head()

0   0 days 00:08:01
1   0 days 00:06:51
2   0 days 00:05:03
3   0 days 00:01:54
4   0 days 00:11:33
Name: duration, dtype: timedelta64[ns]

In [25]:
df["duration_seconds"] = df["duration"].dt.total_seconds()
df["duration_minutes"] = df["duration_seconds"] / 60

df[["duration", "duration_seconds", "duration_minutes"]].head()

         duration  duration_seconds  duration_minutes
0 0 days 00:08:01             481.0          8.016667
1 0 days 00:06:51             411.0          6.850000
2 0 days 00:05:03             303.0          5.050000
3 0 days 00:01:54             114.0          1.900000
4 0 days 00:11:33             693.0         11.550000

In [26]:
df["duration_minutes"].mean()   # average game length across all 2843 games
df["duration_minutes"].max()    # your longest game
df.sort_values("duration_minutes", ascending=False).head()  # your top 5 longest games

,time_class,end_time,white_username,white_rating,white_result,black_username,black_rating,black_result,Date,Result,...,TimeControl,Termination,StartTime,EndDate,EndTime,start_datetime,end_datetime,duration,duration_seconds,duration_minutes
1872,daily,1773970035,AR_Tamil,400,resigned,Azizbek4254,1200,win,2026.03.19,0-1,...,1/86400,Azizbek4254 won by resignation,09:11:41,2026.03.20,01:27:15,2026-03-19 09:11:41,2026-03-20 01:27:15,0 days 16:15:34,58534.0,975.566667
2160,daily,1779132660,Azizbek4254,1060,resigned,lesblancsdabord,1356,win,2026.05.18,0-1,...,1/86400,lesblancsdabord won by resignation,15:22:34,2026.05.18,19:31:00,2026-05-18 15:22:34,2026-05-18 19:31:00,0 days 04:08:26,14906.0,248.433333
2161,daily,1779132683,Azizbek4254,1060,resigned,tberg20,803,win,2026.05.18,0-1,...,1/86400,tberg20 won by resignation,15:23:26,2026.05.18,19:31:23,2026-05-18 15:23:26,2026-05-18 19:31:23,0 days 04:07:57,14877.0,247.950000
1132,rapid,1756049990,Azizbek4254,1257,insufficient,rasuljonov14,803,insufficient,2025.08.24,1/2-1/2,...,900+10,Game drawn by insufficient material,15:22:04,2025.08.24,15:39:50,2025-08-24 15:22:04,2025-08-24 15:39:50,0 days 00:17:46,1066.0,17.766667
595,rapid,1743850321,Azizbek4254,1257,win,TheW3k2nd,1106,checkmated,2025.04.05,1-0,...,900+10,Azizbek4254 won by checkmate,10:37:14,2025.04.05,10:52:01,2025-04-05 10:37:14,2025-04-05 10:52:01,0 days 00:14:47,887.0,14.783333

In [28]:
df.to_csv("chess_games_clean.csv", index=False)